{
	"identifiers": [
		"GHSA-pp84-v3mw-gg4w"
	],
	"identifier": "GHSA-pp84-v3mw-gg4w",
	"package_slug": "pypi/taipy",
	"title": "Taipy 3.1.1 affected by CVEs on flask-core and pymongo",
	"description": "CVEs on latest 3.1.1",
	"date": "2024-08-27",
	"pubdate": "2024-08-27",
	"affected_range": "<=3.1.1",
	"affected_versions": "All versions up to 3.1.1",
	"solution": "Unfortunately, there is no solution available yet.",
	"urls": [
		"https://github.com/advisories/GHSA-pp84-v3mw-gg4w",
		"https://github.com/Avaiga/taipy/security/advisories/GHSA-pp84-v3mw-gg4w",
		"https://github.com/Avaiga/taipy"
	],
	"cwe_ids": [
		"CWE-937",
		"CWE-1035"
	],
	"uuid": "c5b7062b-f9e9-4f87-a4c5-cf0965895e3d"
}
