{
	"identifiers": [
		"CVE-2019-8341"
	],
	"identifier": "CVE-2019-8341",
	"package_slug": "pypi/Jinja2",
	"title": "False Positive",
	"description": "This advisory has been marked as False Positive and removed.",
	"date": "2023-12-19",
	"pubdate": "2019-02-15",
	"affected_range": "<0",
	"affected_versions": "All versions before 0",
	"solution": "Unfortunately, there is no solution available yet.",
	"urls": [
		"https://nvd.nist.gov/vuln/detail/CVE-2019-8341",
		"https://www.exploit-db.com/exploits/46386/"
	],
	"cwe_ids": [
		"CWE-1035",
		"CWE-937",
		"CWE-94"
	],
	"uuid": "6b00a76b-aac8-4ce1-b7b2-122a73f22985",
	"cvss_v2": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
	"cvss_v3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
}
